version: "3.4"

services:  

  zookeeper: 
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN =yes

  kafka:
    image: bitnami/kafka
    restart: always
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENER=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

volumes:
  
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:

  default:
    external:
      name: mydockernetwork